version: "2.1"

services:

  # Media server: Jellyfin
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    user: 1000:1000  # Set user ID and group ID for permissions
    environment:
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
      - TZ=Africa/Casablanca
    volumes:
      - ./configs/jellyfin/etc:/etc/jellyfin
      - ./configs/jellyfin/var-cache:/var/cache/jellyfin
      - ./configs/jellyfin/var-lib:/var/lib/jellyfin
      - ./configs/jellyfin/var-log:/var/log/jellyfin
      - ./configs/jellyfin/timezone:/etc/timezone
      - myMedia:/mnt/media
    group_add:
      - "109"  # Add to video group for hardware acceleration
    network_mode: "host"  # Allows DLNA, remote control, etc.
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128  # GPU access for transcoding
    restart: unless-stopped

  # Browser in a container: Firefox
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined  # Allow graphical access
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Casablanca
      - DRINODE=/dev/dri/renderD128
      - DISABLE_IPV6=true
      - DOCKER_MODS=linuxserver/mods:firefox-fonts
    volumes:
      - ./configs/firefox:/config
    ports:
      - 3001:3001
    networks:
      - firefox
    shm_size: "1gb"  # Shared memory size for better browser performance
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    group_add:
      - "109"
    restart: unless-stopped

  # Backup tool: Duplicati
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Casablanca
    volumes:
      - ./configs/duplicati/config:/config
      - ./configs:/source  # Source to back up
      - ./docker-compose.yml:/source/docker-compose.yml  # Backup the compose file too
      - ./configs/duplicati/restore:/restore
    networks:
      - duplicati
    ports:
      - 8200:8200
    restart: unless-stopped

  # Subtitle downloader: Bazarr
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    networks:
      - mediarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Casablanca
    volumes:
      - ./configs/mediarr/bazarr:/config
      - myMedia:/mnt/media
    ports:
      - 6767:6767
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr

  # Request management for Jellyfin: Jellyseerr
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    hostname: jellyseerr
    networks:
      - mediarr
    user: 1000:1000
    environment:
      - TZ=Africa/Casablanca
    ports:
      - 5055:5055
    volumes:
      - ./configs/mediarr/jellyseerr:/app/config
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr

  # Indexer manager: Prowlarr
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    networks:
      - mediarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Casablanca
    volumes:
      - ./configs/mediarr/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    depends_on:
      - flaresolverr

  # CAPTCHA resolver (for sites like RARBG): FlareSolverr
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    hostname: flaresolverr
    networks:
      - mediarr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Africa/Casablanca
    restart: unless-stopped

  # Torrent client: qBittorrent
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    networks:
      - mediarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Africa/Casablanca
      - WEBUI_PORT=8080
    volumes:
      - ./configs/mediarr/qbittorrent:/config
      - myDlFolders:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  # Movie downloader: Radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    networks:
      - mediarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Africa/Casablanca
    volumes:
      - ./configs/mediarr/radarr:/config
      - myMedia:/mnt/media
      - myDlFolders:/mnt/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on:
      - prowlarr
      - qbittorrent
      - jellyfin

  # eBook downloader: Readarr
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    hostname: readarr
    networks:
      - mediarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Africa/Casablanca
    volumes:
      - ./mediarr/readarr:/config
      - myMedia:/mnt/media
      - myDlFolders:/mnt/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
    depends_on:
      - prowlarr
      - qbittorrent

  # TV series downloader: Sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    networks:
      - mediarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Africa/Casablanca
    volumes:
      - ./configs/mediarr/sonarr:/config
      - myMedia:/mnt/media
      - myDlFolders:/mnt/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    depends_on:
      - prowlarr
      - qbittorrent
      - jellyfin

# Custom networks for isolating containers
networks:
  firefox:
    driver: bridge
  duplicati:
    driver: bridge
  mediarr:
    driver: bridge

# Bind mount media and download folders as named volumes
volumes:
  myMedia:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/media  # Path on host for media library
  myDlFolders:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/HDD/downloads  # Path on host for torrent downloads
